SMTP_USERNAME = VAL
SMTP_PASSWORD = VAL
SMTP_ADDRESS = "smtp.mailgun.org"
SMTP_PORT = 587

EMAIL_FROM_ADDRESS = VAL
EMAIL_BOOKING_ADDRESS = VAL
EMAIL_MAILINGLIST_ADDRESS = VAL
EMAIL_INFO_ADDRESS = VAL
